name: florafolium_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.0+1
  cupertino_icons: ^1.0.8
  permission_handler: ^11.3.1
  image_picker: ^0.8.5+3
  tflite_flutter: ^0.11.0
  #tflite_flutter_helper: ^0.3.0
  logger: ^2.4.0
  image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/background.jpg
  - assets/logo.png
  - assets/upload.png 
  - assets/startcamera.png
  - assets/tips.png
  - assets/leafv7.tflite
  - assets/labels.txt
  - assets/leafdetector/obj.tflite
  - assets/leafdetector/labels.txt

